name: bluevsred
description: A Very Good Project created by Very Good CLI.
version: 1.0.4+4
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_localizations:
    sdk: flutter
  golden_toolkit: ^0.11.0
  intl: ^0.17.0
dev_dependencies:
  bloc_test: ^8.5.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
