name: bluevsred_shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  serverpod_serialization: ^1.2.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  # path: ^1.8.0
  uuid: ^4.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1

