name: bluevsred_client
description: Starting point for a Serverpod client.

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serverpod_client: 2.0.2
  bluevsred_shared:
    path: ../bluevsred_shared
