name: Flutter_Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3.1.0
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2.7.1
        with:
          flutter-version: '3.19.3'
      - name: move to bluevsred_flutter
        run: cd bluevsred_flutter
      - name: Restore packages
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test --coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: hawkbee1/bluevsred